[package]
name = "atm_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[[bin]]
name = "atm"
path = "src/atm.rs"

[[bin]]
name = "bank"
path = "src/bank.rs"